FROM debian:latest
LABEL project="OpenGL Visualiser"
LABEL MAINTAINER Gareth Francis (gfrancis.dev@gmail.com)
RUN apt-get update && apt-get install -y cmake gcc g++ git
RUN apt-get install -y libglfw3-dev libglm-dev

