pipeline {
  agent {
    dockerfile {
      filename 'jenkins/Dockerfile'
      label 'docker-host-dev'
    }
  }
  options {
    buildDiscarder(logRotator(numToKeepStr: '30', artifactNumToKeepStr: '30'))
    timeout(time: 1, unit: 'HOURS')
  }

  stages {
    stage('Git Submodules') { steps {
      sh 'git submodule update --init --recursive'
    } }
    stage('CMake') { steps {
      dir("${env.WORKSPACE}/build") {
        sh "cmake -DCMAKE_INSTALL_PREFIX=${env.WORKSPACE}/install ${env.WORKSPACE}/"
      }
    } }
    stage('Build') {
      steps {
        dir("${env.WORKSPACE}/build") {
          sh '''make install -j$(nproc)'''
        }
      }
    }
    stage('Artifacts') {
      steps {
          sh "tar -C ${env.WORKSPACE}/install/ -cvzf ${env.WORKSPACE}/OpenGL-Visualiser.tar.gz ."
archiveArtifacts artifacts: 'OpenGL-Visualiser.tar.gz', fingerprint: true, onlyIfSuccessful: true
      }
    }
  }

  post {
    always {
emailext attachLog: true, body: '''${DEFAULT_CONTENT}''', compressLog: true, recipientProviders: [[$class: 'CulpritsRecipientProvider']], subject: '${DEFAULT_SUBJECT}', to: '${DEFAULT_RECIPIENTS}'
    }
  }
}

